[package]
name = "suiup"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
reqwest = { version = "0.11", features = ["blocking", "json", "stream"] }
serde = { version = "1.0", features = ["derive"] }
indicatif = "0.17"
whoami = "1.2"
futures-util = "0.3.30"
tokio = { version = "1.39.3", features = ["full"] }
tracing = { version = "0.1.40", features = ["log"] }
console = { version = "0.15.8", features = ["windows-console-colors"] }
tar = "0.4.41"
flate2 = "1.0.31"
anyhow = "1.0.86"
dirs = "5.0.1"
regex = "1.10.6"
serde_json = "1.0.125"
clap_complete = "4.5.40"

